"""Phase 7 Verification: Forecaster Mission-Control Dashboard (React + Leaflet + Recharts)."""

import os
import sys
from pathlib import Path

sys.path.insert(0, os.path.abspath(os.path.join(os.path.dirname(__file__), "..")))

from src.core.logger import logger

FRONTEND_DIR = Path(__file__).resolve().parent.parent / "frontend"

PASS = "[OK]"
FAIL = "[FAIL]"


def check(label: str, condition: bool, detail: str = ""):
    symbol = PASS if condition else FAIL
    msg = f"  {symbol} {label}"
    if detail:
        msg += f": {detail}"
    logger.info(msg)
    if not condition:
        raise AssertionError(f"FAILED: {label}")


def run_verification():
    logger.info("=" * 65)
    logger.info("SIH 2026 PS 26070 — Phase 7: Forecaster Dashboard Verification")
    logger.info("=" * 65)

    # ── 1. Directory Structure ──────────────────────────────────────────
    logger.info("\n[1/4] Checking Frontend Architecture & Dependencies...")
    check("Frontend root directory exists", FRONTEND_DIR.exists())
    check("package.json exists", (FRONTEND_DIR / "package.json").exists())
    check("node_modules installed", (FRONTEND_DIR / "node_modules").exists())
    check("Vite config present", (FRONTEND_DIR / "vite.config.js").exists())

    # ── 2. Component Inventory ──────────────────────────────────────────
    logger.info("\n[2/4] Verifying Dashboard Components...")
    components = [
        ("Navbar Header & Status Bar", "Navbar.jsx"),
        ("Leaflet Geospatial Map Layer", "Map/CycloneMap.jsx"),
        ("Intensity & Central Pressure Card", "Intensity/IntensityCard.jsx"),
        ("Rapid Intensification Gauge Card", "RapidIntensification/RICard.jsx"),
        ("Grad-CAM Explainability Viewer", "Explainability/GradCAMViewer.jsx"),
        ("Coastal Risk Matrix Table", "RiskMatrix/RiskMatrix.jsx"),
        ("IMD Warning Bulletin Modal", "BulletinViewer/BulletinViewer.jsx"),
        ("Forecaster Sign-Off Modal", "ForecasterReview/ForecasterReviewModal.jsx"),
        ("Historic Storm Simulator Bar", "SimulationControls/SimulationBar.jsx"),
    ]
    for name, rel_path in components:
        path = FRONTEND_DIR / "src" / "components" / rel_path
        check(f"{name} ({rel_path})", path.exists())

    # ── 3. Design System & API Layer ────────────────────────────────────
    logger.info("\n[3/4] Verifying Tactical Dark Theme & Resilient API Client...")
    index_css = FRONTEND_DIR / "src" / "index.css"
    check("index.css exists with design tokens", index_css.exists())
    with open(index_css, "r", encoding="utf-8") as f:
        css_content = f.read()
    check("Glassmorphism and tactical CSS tokens defined", "--color-bg-glass" in css_content)
    check("Pulse animation for RI defined", "pulse-ring" in css_content)

    api_js = FRONTEND_DIR / "src" / "api.js"
    check("api.js exists with offline fallback cache", api_js.exists())
    with open(api_js, "r", encoding="utf-8") as f:
        api_content = f.read()
    check("MOCK_STORM_STATE defined for zero-crash presentation", "MOCK_STORM_STATE" in api_content)

    # ── 4. Production Build Verification ────────────────────────────────
    logger.info("\n[4/4] Verifying Production Distribution Bundle...")
    dist_dir = FRONTEND_DIR / "dist"
    check("dist/ directory generated by Vite", dist_dir.exists())
    check("dist/index.html present", (dist_dir / "index.html").exists())
    js_bundles = list((dist_dir / "assets").glob("*.js"))
    css_bundles = list((dist_dir / "assets").glob("*.css"))
    check("Minified JS bundle created", len(js_bundles) > 0, f"file={js_bundles[0].name if js_bundles else 'none'}")
    check("Minified CSS bundle created", len(css_bundles) > 0, f"file={css_bundles[0].name if css_bundles else 'none'}")

    logger.info("\n" + "=" * 65)
    logger.info("PHASE 7 VERIFICATION COMPLETED SUCCESSFULLY: ALL CHECKS PASSED!")
    logger.info("=" * 65)


if __name__ == "__main__":
    run_verification()
